# Generated by Django 2.1.7 on 2019-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectwotan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaker',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ice',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
