# Generated by Django 2.1.7 on 2019-03-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectwotan', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaker',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ice',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='strength',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ice',
            name='strength',
            field=models.IntegerField(default=-1),
        ),
    ]
