# Generated by Django 2.1.7 on 2019-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectwotan', '0003_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaker',
            name='is_nisei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ice',
            name='is_nisei',
            field=models.BooleanField(default=False),
        ),
    ]
